### ISSUE TITLE
missing s3dg_flow model for kinectics_400

### ISSUE THREAD

**Issue by ray342649093** [princeton-vl/d3dhelper#1]
It seems that the s3dg_flow model for kinectics_400 is missing. Also, there are two s3dg_rgb model for kinectic_600. one of them (the last one) is actually a flow model for 600 classes as the input channel for the first conv layer is 2. Hopefully, the s3dg_flow model for kinectics_400 could be uploaded soon.

**Comment by jonathancstroud** [comment]
Thanks for catching this! I've fixed the error and uploaded the flow model for Kinetics-400.
