### ISSUE TITLE
How do you sample frames for training? 

### ISSUE THREAD

**Issue by TengdaHan** [princeton-vl/d3dhelper#4]
Hi @jonathancstroud 
The example code reads the first 64 frames of kinetics video as input. 
I wonder how do you sample frames from videos during training? e.g. how many frames do you sample per video, what frame rate, do you randomly sample a clip, do you have different settings for Kinetics400, UCF101 and HMDB51? 
Thank you very much!

**Comment by jonathancstroud** [comment]
Hello, and thank you for you interest in this work. During training, we sample 64 frames per video at 25 frames per second. The clips are randomly chosen from the 10-second video (250 frames total). The video frames are each resized to 256x256 and then we take a 224x224 random crop. We use the same settings for training on all datasets, padding the clips if necessary.

**Comment by TengdaHan** [comment]
So you randomly sample 64/25=2.5 seconds from each 10-second video, right?

**Comment by jonathancstroud** [comment]
Yes, that is correct.
